In [1]:
import sys
import os

# ścieżka do folderu głównego projektu
project_root = os.path.abspath("..")
sys.path.append(project_root)

print(project_root)

/mnt/windows/Users/mikołaj/Desktop/dokumenty/studia/2025-2026L/mocadr/laby/project_1/project1_s324671


In [8]:
from modules.models.nmf_model import NMFRecommender

In [9]:
train_path = "../data/ratings.csv"
model_path = "../models_trained/test_model.pkl"

In [10]:
import sys
import os
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

# setup ścieżek
project_root = os.path.abspath("..")
sys.path.append(project_root)

from modules.models.nmf_model import NMFRecommender

# ścieżki
train_path = "../data/ratings.csv"
model_path = "../models_trained/test_model.pkl"

# load data
df = pd.read_csv(train_path)
print("Data shape:", df.shape)

# train
model = NMFRecommender(
    n_components=10,
    imputation_strategy="movie_mean"
)

model.fit(df)
print("Model trained")

# test predykcji
test_pairs = df.sample(10)[["userId", "movieId"]]
preds = model.predict(test_pairs)

print("\nSample predictions:")
print(preds)

# test zapisu
model.save(model_path)
print("\nModel saved")

# test wczytania
loaded_model = NMFRecommender.load(model_path)
preds2 = loaded_model.predict(test_pairs)

print("\nCompare predictions:")
print(preds[:5])
print(preds2[:5])

# RMSE test
sample = df.sample(1000)
pairs = sample[["userId", "movieId"]]
true_ratings = sample["rating"].values

preds = model.predict(pairs)
rmse = np.sqrt(mean_squared_error(true_ratings, preds))

print("\nRMSE:", rmse)

# cold start test
cold_test = pd.DataFrame({
    "userId": [999999, df["userId"].iloc[0]],
    "movieId": [df["movieId"].iloc[0], 999999]
})

print("\nCold start test:")
print(loaded_model.predict(cold_test))

Data shape: (100836, 4)


/mnt/windows/Users/mikołaj/Desktop/dokumenty/studia/2025-2026L/mocadr/laby/project_1/project1_s324671/.venv/lib/python3.10/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 300 reached. Increase it to improve convergence.
  warnings.warn(


Model trained

Sample predictions:
[4.  3.5 3.5 1.5 2.5 4.  4.  3.5 3.  3.5]

Model saved

Compare predictions:
[4.  3.5 3.5 1.5 2.5]
[4.  3.5 3.5 1.5 2.5]

RMSE: 0.8520563361656317

Cold start test:
[4.  4.5]
